# permissions for end users to view exampleresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-serviceaccount-hijacking-protection
    app.kubernetes.io/managed-by: kustomize
  name: exampleresource-viewer-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - exampleresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.example.com
  resources:
  - exampleresources/status
  verbs:
  - get
